# Generated by Django 3.0.2 on 2020-04-18 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=30, null=True)),
                ('packageid', models.BigIntegerField()),
                ('destx', models.IntegerField(null=True)),
                ('desty', models.IntegerField(null=True)),
                ('packagestatus', models.CharField(choices=[('created', 'created'), ('in the warehouse', 'in the warehouse'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='created', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('truckid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingNumber', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckid', models.IntegerField()),
                ('truckstatus', models.CharField(choices=[('idle', 'idle'), ('on the way to warehouse', 'on the way to warehouse'), ('arrived at warehouse', 'arrived at warehouse'), ('delivering', 'delivering')], default='idle', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
